
const ROUTES = {
    // Admin Routes
    ADMIN: {
        BASE: '/admin',
        LOGIN: '/login',
        LOGOUT: '/logout',
        SIGNOUT2: '/signout2', 
        HOME: '/home',
        PRODUCT_LIST: '/productlist',
        DELETE_PRODUCT: '/productlist/:id',
        ADD_PRODUCT: '/addproduct',
        EDIT_PRODUCT: '/editproduct/:Id',
        DELETE_IMAGE: '/deleteimage/:productId/:index',
        EDIT_PRODUCT_POST: '/editproduct/:productId',
        ADD_PRODUCT_POST: '/addproduct',
        CUSTOMERS: '/customers',
        TOGGLE_BLOCK_USER: '/customers/:userId/toggle-block',
        CATEGORY: '/category',
        EDIT_CATEGORY: '/category/:id',
        ADD_CATEGORY: '/category',
        GET_EDIT_CATEGORY: '/editcategory/:id',
        DELETE_CATEGORY: '/deletecategory/:id',
        ORDER: '/order',
        UPDATE_ORDER: '/updateorder',
        APPROVE_REQUEST: '/approve-request',
        COUPON: '/coupon',
        AVAILABLE_COUPONS: '/available',
        GET_COUPON_BY_ID: '/coupon/:id',
        UPDATE_COUPON: '/coupon/:id',
        DELETE_COUPON: '/coupon/:id',
        SALES: '/sales',
        PDF: '/pdf',
        EXCEL: '/excel',
        DOUGHNUT_GRAPH: '/doughnut-graph',
        DOUGHNUT_CATEGORY_GRAPH: '/doughnut-category-graph'
    },
    
    // User Routes
    USER: {
        BASE: '/',
        LOGIN: '/login',
        REGISTER: '/getRegister',
        FORGOT_PASSWORD: '/forgotpassword',
        VERIFY_FORGOT_OTP: '/verifyforgototp',
        RESEND_FORGOT_OTP: '/resendforgototp',
        CHANGE_PASSWORD: '/changeCpassword',
        CATEGORY: '/category/:id',
        CHECK_REFERRAL_CODE: '/checkReferralCode',
        LOGOUT: '/logout',
        HOME: '/home',
        FOR_HER: '/forher',
        FOR_HIM: '/forhim',
        DISPLAY: '/display/:id',
        CART_VIEW: '/cartView',
        ADD_TO_CART: '/cart',
        GET_CART: '/getcart/:userId',
        GET_CART_NUMBER: '/getcartnumber/:userId',
        CHECKOUT: '/checkout',
        CHECKOUT_ERROR: '/checkouterror',
        RETRY_CHECKOUT: '/retry-checkout',
        CREATE_RAZORPAY_ORDER: '/create-razorpay-order',
        VERIFY_RAZORPAY_PAYMENT: '/verify-razorpay-payment',
        UPDATE_ORDER_STATUS: '/update-order-status',
        CHECK_WALLET: '/check-wallet',
        UPDATE_WALLET: '/update-wallet',
        ORDER: '/order',
        ORDER_HISTORY: '/orderhistory',
        GENERATE_INVOICE: '/generate-invoice/:orderId',
        SIGNOUT: '/signout',
        CHANGE_PASS: '/changepass',
        OTP_GET: '/otpget',
        RESEND_OTP: '/resendotp',
        UPDATE_QUANTITY: '/updateQuantity',
        REMOVE_FROM_CART: '/removeFromCart/:productId',
        CANCEL_ORDER: '/cancel-order/:orderId',
        INITIATE_RETURN: '/initiate-return/:orderId',
        INITIATE_REFUND: '/initiate-refund/:orderId',
        VERIFY_OTP: '/verifyotp',
        ADDRESS: '/address',
        PROFILE: '/profile',
        ADD_ADDRESS: '/Address',
        DELETE_ADDRESS: '/delete/:id',
        EDIT_PROFILE: '/editprofile/:userID',
        EDIT_ADDRESS: '/addressedit/:id',
        GET_EDIT_ADDRESS: '/Editaddress/:i',
        WISHLIST_PAGE: '/wishlistPage',
        WISHLIST_INFO: '/wishlistInfo',
        REMOVE_FROM_WISHLIST: '/wishlistRemove',
        WALLET: '/wallet',
        GENERATE_WALLET_RAZORPAY: '/generate-razorpay-order',
        CREATE_REFERRAL: '/createReferral',
        VALIDATE_COUPON: '/validate-coupon',
        CHECK_PAYMENT_LOCK: '/check-payment-lock',
        RELEASE_PAYMENT_LOCK: '/release-payment-lock'
    }
};

module.exports = ROUTES;